services:
  eshopwebmvc:
    image: eshoponweb-eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - "sqlserver"
  eshoppublicapi:
    # image: ${DOCKER_REGISTRY-}eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
  catalog-service:
    image: eshoponweb-catalog-service
    build:
      context: .
      dockerfile: .\eShopOnWebStrangler\eShopOnWebCatalog\Dockerfile
    depends_on:
      - rabbitmq
      - sqlserver
      - catalog-sql-server
    restart: unless-stopped
  inventory-service:
    image: eshoponweb-inventory-service
    build:
      context: .
      dockerfile: .\eShopOnWebStrangler\InventoryManagementSystem\Dockerfile
    depends_on:
      - inventory-sql-server
      - rabbitmq
  catalog-sql-server:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1434:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
  inventory-sql-server:
    image: mcr.microsoft.com/mssql/server
  # api-gateway:
  #   image: eshoponweb-api-gateway
  #   build:
  #     context: .
  #     dockerfile: .\eShopOnWebStrangler\APIGateway\Dockerfile
  #   environment:
  #     - catalogHost=catalog-service
  #     - catalogPort=8080
  #   ports:
  #     - "5050:8080"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # Port for RabbitMQ messaging
      - "15675:15672" # Port for RabbitMQ management UI

